### ISSUE TITLE
Export the tests with the Recorder Codeception extension 

### ISSUE THREAD

**Issue by javigomez** [joomla-extensions/weblinks#159]
After adding this code to ./codeception.yml:

```yml
     ...
     memory_limit: 1024M
 extensions:
    enabled: [Codeception\Extension\Recorder]
    config:
        Codeception\Extension\Recorder:
            delete_successful: false
            module: JoomlaBrowser 
```

You can get awesome reports for acceptance test like the one in the attached file:

http://www.youtube.com/watch?v=kN3dsqtsSTQ
